import fs from 'fs';
import path from 'path';
import React from 'react';
import Head from 'next/head';
import dynamic from 'next/dynamic';
import { Box } from '@mui/material';
import { getEnv } from 'environment';

import 'swagger-ui-react/swagger-ui.css';
/* @ts-ignore */
const SwaggerUI = dynamic<{ url: string }>(import('swagger-ui-react'), {
  ssr: false,
});

const env = getEnv();
const swaggerFolder =
  env.SERVER_ENV === 'local'
    ? path.resolve(__dirname, 'api', 'swagger')
    : './swagger.json';

const Swagger: React.FC = () => (
  <Box>
    <Head>
      <title>Swagger</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <SwaggerUI url={swaggerFolder} />
  </Box>
);
export default Swagger;
